---
tenants:
  - name: DC1
    vrfs:
      - name: default
        svis:
          - id: 110
            name: 'DC1_DATA_110'
            enabled: true
            ip_virtual_router_addresses:
              - 10.1.10.1
            nodes:
              - node: spine-1
                ip_address: 10.1.10.2/24
              - node: spine-2
                ip_address: 10.1.10.3/24