# ---

# port_profiles:

#   - profile: vlan20
#     mode: "trunk"
#     vlans: "20"
#     spanning_tree_portfast: edge
#     dot1x:
#       port_control: "auto"
#       reauthentication: true
#       pae:
#         mode: "authenticator"
#       authentication_failure:
#         action: "allow"
#         allow_vlan: 999
#       host_mode:
#         mode: "multi-host"
#         multi_host_authenticated: true
#       mac_based_authentication:
#         enabled: true
#       timeout:
#         reauth_period: "server"
#         tx_period: 3
#       reauthorization_request_limit: 3

# network_ports:
#   - switches:
#       - leaf-[12][ab]
#     switch_ports:
#       - Ethernet1-48
#     profile: vlan20