---
tenants:
  - name: DC1
    vrfs:
      - name: default
        svis:
          - id: 20
            name: 'DC1_DATA_20'
            enabled: true
            ip_virtual_router_addresses:
              - 10.1.20.1
            nodes:
              - node: spine-1
                ip_address: 10.1.20.2/24
              - node: spine-2
                ip_address: 10.1.20.3/24
