---
name: Deploy Configs to Digital Twin

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy_configs:
    name: Deploy Configs to Digital Twin
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          ansible-galaxy collection install -r requirements.yml

      - name: Deploy Configs to Digital Twin CV Instance
        env:
          ACT_CV_TOKEN: ${{ secrets.ACT_CV_TOKEN }}
        run: |
          make deploy-dc1_dt

  post_change_validation:
    name: Post-Change Validation of Digital Twin Environment
    needs: [deploy_configs]
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          ansible-galaxy collection install -r requirements.yml

      - name: Run ANTA Against Digital Twin CV Instance - Post Deploy
        run: |
          make validate-dc1_dt

      - name: Save output
        run: |
            cat sites/dc1/digital_twin/anta/reports/anta_report.md >> $GITHUB_STEP_SUMMARY

  deploy_prod_trigger:
    name: Repository Dispatch
    needs: [ post_change_validation ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
              github.rest.repos.createDispatchEvent({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  event_type: "mkdocs"
              })
